language: 'ruby'
rvm:
  - '2.1.4'
script:
  - 'RAILS_ENV=test bundle exec rake --trace db:migrate spec'
before_script:
  - mysql -e 'create database tap_test'
  - psql -c 'create database tap_test' -U postgres

